### ISSUE TITLE
bug: Rocksky: Error encountered while getting User listens

### ISSUE THREAD

**Issue by kruoni** [FoxxMD/multi-scrobbler#391]
### Please check existing knowledge before opening an issue

- [x] I have [checked the FAQ](https://foxxmd.github.io/multi-scrobbler/docs/FAQ/) and [documentation](https://foxxmd.github.io/multi-scrobbler/docs/configuration/)
- [x] I have [searched through existing issues](https://github.com/FoxxMD/multi-scrobbler/issues?q=sort%3Aupdated-desc) and [discussions.](https://github.com/FoxxMD/multi-scrobbler/discussions)

### Describe the Bug

Seems like Multi Scrobbler cannot access Rocksky recent scrobbles (which could cause issues if there are duplicate scrobbles?)

### Platform

Docker

### Versions

- Multiscrobbler: 0.10.1
- Rocksky: (?)
- jellyfin: 10.11.2

### Logs

```shell
[2025-11-09 20:19:39.853 +0100] DEBUG  : [App] [Scrobblers] [Listenbrainz - KuoSky] Found 0 recent scrobbles
[2025-11-09 20:19:39.851 +0100] ERROR  : [App] [Scrobblers] [Listenbrainz - KuoSky] [API - ListenBrainz - KuoSky] Error encountered while getting User listens | Error =>  Cannot read properties of undefined (reading 'trim')
[2025-11-09 20:19:39.752 +0100] DEBUG  : [App] [Scrobblers] [Listenbrainz - KuoSky] Refreshing recent scrobbles
[2025-11-09 20:19:39.751 +0100] VERBOSE: [App] [Scrobblers] [Listenbrainz - KuoSky] Fetching up to 100 initial scrobbles...
[2025-11-09 20:19:39.750 +0100] DEBUG  : [App] [Scrobblers] [Listenbrainz - KuoSky] [Now Playing] Enabled by default config
[2025-11-09 20:19:39.748 +0100] INFO   : [App] [Scrobblers] [Listenbrainz - KuoSky] Fully Initialized!
[2025-11-09 20:19:39.449 +0100] VERBOSE: [App] [Scrobblers] [Listenbrainz - KuoSky] Connection check succeeded
[2025-11-09 20:19:39.447 +0100] VERBOSE: [App] [Scrobblers] [Listenbrainz - KuoSky] [API - ListenBrainz - KuoSky] Listenbrainz Host does not look like a Koito server.
[2025-11-09 20:19:39.304 +0100] VERBOSE: [App] [Scrobblers] [Listenbrainz - KuoSky] Parsing caching succeeded => Scrobbles from Cache: 0 Queue | 0 Dead Letter
[2025-11-09 20:19:39.302 +0100] VERBOSE: [App] [Scrobblers] [Listenbrainz - KuoSky] Building required data init succeeded
[2025-11-09 20:19:39.301 +0100] DEBUG  : [App] [Scrobblers] [Listenbrainz - KuoSky] Attempting to initialize...
```

**Comment by FoxxMD** [comment]
Thanks for the report. Looks like I was a little overzealous adding Rocksky, it only supports scrobble endpoints but not the scrobble fetching endpoint MS needs to detect duplicates and do some other things...I need to implement a proper client for it!

**Comment by FoxxMD** [comment]
@kruoni please try using docker image `foxxmd/multi-scrobbler:pr-392` with configuration instructions from [PR-392](https://github.com/FoxxMD/multi-scrobbler/pull/392#issuecomment-3512602082).

For some reason Rocksky seems to be ignoring all the scrobbles I send when it had previously worked fine with MS. Let me know if you see the same thing -- use `DEBUG_MODE=true` as an env in MS and you should see log lines containing text like this after a scrobble is submitted:

```
Submit Response: {"payload":{"ignored_listens":1,"submitted_listens":0},"status":"ok"}
```

If it contains `"submitted_listens":1` then it saved the scrobble, if it has `ignored_listens` then Rocksky chose to discard them.

EDIT: I've brought up the issue with the Rocksky dev so hopefully a resolution soon. But if you have any ignored scrobbles please post the payload shown in the log, along with the response. More data points will help, thanks.

**Comment by kruoni** [comment]
Got the same issue here, scrobbles are now ignored, while on other clients it is fine.

If you need more logs I will happily provide them.

```
[2025-11-10 17:48:20.910 +0100] DEBUG  : [App] [Scrobblers] [Rocksky - KuoSky] [API - RockSky - KuoSky] Submit Response: {"payload":{"ignored_listens":1,"submitted_listens":0},"status":"ok"}
[2025-11-10 17:48:20.742 +0100] DEBUG  : [App] [Scrobblers] [Rocksky - KuoSky] [API - RockSky - KuoSky] Submit Payload: {"listen_type":"single","payload":[{"listened_at":1762793262,"track_metadata":{"artist_name":"Toby Fox","track_name":"Lancer","release_name":"DELTARUNE Chapter 1 (Original Game Soundtrack)","additional_info":{"duration":48,"submission_client":"multi-scrobbler","submission_client_version":"pr392-5abe0bc","artist_names":["Toby Fox"],"release_artist_name":"Toby Fox","release_artist_names":["Toby Fox"],"music_service_name":"Jellyfin"}}}]}
[2025-11-10 17:48:20.739 +0100] DEBUG  : [App] [Scrobblers] [Rocksky - KuoSky] Toby Fox - Lancer @ 2025-11-10T17:47:42+01:00 (S) => No Match because no recent scrobbles returned from API
[2025-11-10 17:48:20.735 +0100] DEBUG  : [App] [Scrobblers] [Rocksky - KuoSky] Found 0 recent scrobbles
[2025-11-10 17:48:20.245 +0100] DEBUG  : [App] [Scrobblers] [Rocksky - KuoSky] Refreshing recent scrobbles
[2025-11-10 17:48:20.244 +0100] DEBUG  : [App] [Scrobblers] [Rocksky - KuoSky] [Upstream Refresh] Should refresh => newest queued scrobble playDate is newer than last refresh
[2025-11-10 17:48:19.823 +0100] DEBUG  : [App] [Scrobblers] [Rocksky - KuoSky] Updated queued scrobble cache
[2025-11-10 17:48:19.823 +0100] DEBUG  : [App] [Scrobblers] [Lastfm - KuoFM] Updated queued scrobble cache
[2025-11-10 17:48:19.819 +0100] DEBUG  : [App] [Sources] [Jellyfin - KuoFin] Last activity was at 17:48:19+01:00 | Next check in 10.00s
[2025-11-10 17:48:19.818 +0100] INFO   : [App] [Sources] [Jellyfin - KuoFin] Discovered => Toby Fox - Lancer @ 2025-11-10T17:47:42+01:00 (S)
```

**Comment by FoxxMD** [comment]
Thanks for giving it a try. Issue for ignored scrobbles is [here](https://tangled.org/@rocksky.app/rocksky/issues/7) if you want to follow along. I'll update this when there is progress.

**Comment by FoxxMD** [comment]
I have merged the PR into the master branch. The rocksky changes are available in the `edge` docker tag, or just keep using the one you already are.

I'm pretty sure the ignored scrobbles issue is on the rocksky side so there is no need for changes on the MS side. Once its fixes everything should start working immediately.

If any further changes are required I'll update this issue.

**Comment by FoxxMD** [comment]
Fix released in [0.10.2](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.10.2)

If any further changes are needed after Rocksky fixes things on their end I'll update this issue again

**Comment by FoxxMD** [comment]
@kruoni please update your docker image to `latest` or [0.10.3](https://github.com/FoxxMD/multi-scrobbler/releases/tag/0.10.3). There are a few fixes for rocksky. I've also worked with the developer to get a fix in for the ignored scrobbles. After updating, everything should now be working.

**Comment by kruoni** [comment]
For some reason the API bug is still present for me? 

I updated and remade my config (since I first decided to removed RockSky for tealfm), but the bug is still present even on 0.10.3.

Is it an issue on Rocksky's part that I need to wait for it to be fixed or just myself being unlucky again 🥲.

```
[2025-11-17 23:01:58.052 +0100] ERROR  : [App] [Scrobblers] [Rocksky - KuoRock] Could not scrobble Good Kid - Wall @ 2025-11-17T22:58:43+01:00 (S) from Source 'Jellyfin - KuoFin' due to error
Error: Could not scrobble Good Kid - Wall @ 2025-11-17T22:58:43+01:00 (S) from Source 'Jellyfin - KuoFin' due to error
    at RockskyScrobbler.processDeadLetterScrobble (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:892:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async <anonymous> (CWD/src/backend/server/api.ts:364:35)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: Error occurred while making Rocksky API scrobble request: Listenbrainz API Request Failed => (HTTP Status 400)
    at RockskyScrobbler.doScrobble (CWD/src/backend/scrobblers/RockskyScrobbler.ts:99:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RockskyScrobbler.processDeadLetterScrobble (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:885:39)
    at async <anonymous> (CWD/src/backend/server/api.ts:364:35)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: Listenbrainz API Request Failed => (HTTP Status 400)
    at RockSkyApiClient.callLZApi (CWD/src/backend/common/vendor/RockSkyApiClient.ts:98:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RockSkyApiClient.submitListen (CWD/src/backend/common/vendor/RockSkyApiClient.ts:191:26)
    at async RockskyScrobbler.doScrobble (CWD/src/backend/scrobblers/RockskyScrobbler.ts:85:26)
    at async RockskyScrobbler.processDeadLetterScrobble (CWD/src/backend/scrobblers/AbstractScrobbleClient.ts:885:39)
    at async <anonymous> (CWD/src/backend/server/api.ts:364:35)
    at async wrappedMiddleware (CWD/node_modules/@awaitjs/express/index.js:116:7)
caused by: Error: Bad Request
    at callback (CWD/node_modules/superagent/src/node/index.js:901:17)
    at IncomingMessage.<anonymous> (CWD/node_modules/superagent/src/node/index.js:1166:18)
    at IncomingMessage.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by kruoni** [comment]
Well I retract my comment, it seems like it now decided to work. As usual I'll monitor it and make a new issue if the bug persists. Thanks for all the fixes!

**Comment by kruoni** [comment]
Sorry for making a lot of comments, but despite `"submitted_listens":1` being correct and multiscrobbler reporting having scrobbled the track, nothing shows on my profile.

I have seen your own scrobbles being detected on RockySky (as they are the last which is a bit surprising) is it an issue on RockSky's side?

Also, the API issue still happens, but not every time.

I'll try to make a new issue when I'll be on my computer tomorrow if I remember.

**Comment by FoxxMD** [comment]
I think maybe there is an issue with the service, as a whole. I do see that all scrobbles on their discord seem to have stopped being posted

**Comment by FoxxMD** [comment]
@kruoni 

<img width="608" height="201" alt="Image" src="https://github.com/user-attachments/assets/c89fe786-f2b1-40f4-883b-8a5c56e0e5c3" />

After cloudflare recovers you'll need to log out and then log back in to Rocksky before scrobbling should be back to normal. No need to renew api keys, just logging back in should do it.

**Comment by kruoni** [comment]
For some reason, I still get an error 400 while trying to scrobble, works fine for the other clients. The error is the same as the last logs I've uploaded.

I will try to sign out and log in on my computer to see if it does something but it seems like I'm really unlucky here.

Also, not all successfully scrobbled tracks gets shown on RockSky.
